#!/usr/bin/env bash
# Use ifconfig to get information about network interfaces and IP addresses
ifconfig | grep -oE "inet (addr:)?([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)" | awk '{print $2}' | sed 's/addr://'

